# Generated by Django 6.0.4 on 2026-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_file_post_file_name_post_file_size_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
